<?php
    $languageArray = array(
        // TITLE
        'Accueil.php' => 'HOME V7',
        'Creer_personne.php' => 'CREATE PERSON V7',
        'Afficher_personne.php' => 'DISPLAY PERSON V7',
        'Modifier_personne.php' => 'MODIFY PERSON V7',
        'Login.php' => 'LOGIN V7',
        '403.php' => '403 V7',
        '404.php' => '404 V7',

        // LANGUAGE
        'language' => '🌍 Select language',
        'french' => '🇫🇷 French',
        'english' => '🇬🇧 English',
        'catalan' => '🏴‍☠️ Catalan',
        // LINK
        'home_page' => 'Go back home',
        'create_page' => 'Create Person',
        'display_page' => 'display Person',
        'login_page' => 'Login page',
        // PAGES
        'man' => 'man',
        'woman' => 'woman',
        'other' => 'other',
        'admin' => 'administrator',
        'user' => 'user',
        'person' => 'Person',
        'id' => 'Id',
        'firstname' => 'Firstname',
        'lastname' => 'Lastname',
        'age' => 'Age',
        'mail' => 'Mail',
        'gender' => 'Gender',
        'role' => 'Role',
        'modify' => 'Modify',
        'modify_icon' => 'MOD',
        'delete' => 'Delete',
        'delete_icon' => 'SUP',
        'data' => 'Data',
        'year_old' => 'Y.Old',
        'select_gender' => 'Select gender',
        'select_role' => 'Select role',
        'create' => 'Create',
        'cancel' => 'Cancel',
        'modify_data' => 'Modify Data',
        'username' => 'User',
        'password' => 'Password',
        'connect' => 'Connection',
        // MESSAGE
        'login_message_missing' => 'username or password not filled in',
        'login_message_false' => 'incorrect username or password',
        'DB_access_broken' => 'unable to connect to DB',

        'create_message_error' => 'Please fill all the fields',
        'create_message_success' => 'Person created successfully',
        'create_message_error_2' => 'Person not created',
        'delete_message_success' => 'Person deleted from the DB',
        'guest' => 'Guest',
        'logout' => 'Logout',
        'hello_message'=> 'Hello ',
        'home_message' => 'You are connected as : ',
        'home_message_2' => 'You must be connected to access this page',
        'home_message_3' => 'Go to the ',
        '403_message_1' => 'You shall not pass',
        '404_message_1' => 'ERROR 404'
    );
?>