<?php 
    $langArray = array(

        "languefr"=>"French",
        "langueen"=>"English",
        "langue"=>"",
        "titre"=> "Homepage",
        "accesbase"=>"Database problem  access ",
        "liste"=>"List of person",
        "creapers"=>"Create new profil",
        "copyright"=>"COPYRIGHT 2023  © R.GONZALVEZ",
        "id"=>"Id",
        "prenom"=>"Surname",
        "nom"=>"Name",
        "mail"=>"E-mail",
        "age"=>"Age",
        "genre"=>"Gender",
        "role"=>"Role",
        "modifier"=>"Modify",
        "supprimer"=>"Delete",
        "valider"=>"Confirm",
        "revenir"=>"Back to homepage",
        "creation"=>" New profil Create",
        "champ"=>"Required",
        "renseignement"=>"Renseignement",
        "perssup"=>"Person deleted",
        "perssupfail"=>"Person not deleted",
        "nonrens"=>"Undefined",
        "perscrea"=>"Person create",
        "perscreafail"=>"Person isn't create",
        "imposs"=>"Impossible get a connexion ",
        "modif"=>"Modify in progress ",
        "choix"=>"Choice =>",
        "cara"=>"Characteristic of person",
        "crea"=>"Creation",
        "ho"=>"Man",
        "fem"=>"Woman",
        "pass"=>"Password",
        "user"=>"Login",
        "connect"=>"Connect here",
        "deja"=>"Already register ?",
        "backto"=>"Back To Front",
        "deco"=>"Disconnexion",
        "nouveau"=>"Are you a new visitor ?",
        "inscr"=>"Register",
        "connex"=>"connexion",
        "enter"=>"Enter your ",

        "util"=>"User",
        "effacer"=>"Delete",
        "Modcour"=>"Update in progress",
        "admini"=>"Administrator"
    )
?>