<?php 
    $langArray = array(
        
        "languefr"=>"Francais",
        "langueen"=>"Anglais",
        "langue"=>"",
        "titre"=> "Page d'accueil",
        "accesbase"=>"Probleme d'accés a la base de données",
        "liste"=>"Liste des personnes",
        "creapers"=>"Création de nouveaux profils",
        "copyright"=>"COPYRIGHT 2023 © R.GONZALVEZ",
        "id"=>"Id",
        "prenom"=>"Prénom",
        "nom"=>"Nom",
        "mail"=>"Courriel",
        "age"=>"Age",
        "genre"=>"Genre",
        "role"=>"Role",
        "modifier"=>"Modifier",
        "supprimer"=>"Supprimer",
        "valider"=>"Valider",
        "revenir"=>"Revenir à la page d'accueil",
        "creation"=>"Creation d 'une  nouvelle personne",
        "champ"=>"Champs obligatoire",
        "renseignement"=>"Renseignement",
        "perssup"=>"Personne supprimé",
        "perssupfail"=>"Personne n'est supprimé",
        "nonrens"=>"Non renseigné",
        "perscrea"=>"Personne créee",
        "perscreafail"=>"Personne non créee",
        "imposs"=>"Impossible etablir une connexion",
        "modif"=>"En cours de modification ",
        "choix"=>"Choix =>",
        "cara"=>"Caracteristique de la personne",
        "crea"=>"Création",
        "ho"=>"Homme",
        "fe"=>"Femme",
        "pass"=>"Mot de passe",
        "user"=>"Nom emprunt",
        "connect"=>"Connectez-vous ici",
        "deja"=>"Déja inscrit ?",
        "backto"=>"Back To Front",
        "deco"=>"Déconnexion",
        "nouveau"=>"Vous étes nouveau ici ?",
        "inscr"=>"S'inscrire",
        "connex"=>"connexion",
        "enter"=>"Entrez votre ",
        "modification"=>"Modification du profil ",


        "util"=>"Utilisateur",
        "effacer"=>"Effacer",
        "Modcour"=>"Modification en cours",
        "admini"=>"Administrateur"
    )
?>