<?php
    $languageArray = array(
        // TITLE
        'Accueil.php' => 'HOME V6',
        'Creer_personne.php' => 'CREATE PEOPLE V6',
        'Afficher_personne.php' => 'DISPLAY PEOPLE V6',
        'Modifier_personne.php' => 'MODIFY PEOPLE V6',
        'Login.php' => 'LOGIN V6',

        // LANGUAGE
        'language' => '🌍 Select language',
        'french' => '🇫🇷 French',
        'english' => '🇬🇧 English',
        'catalan' => '🏴‍☠️ Catalan',
        // LINK
        'home_page' => 'Go back home',
        'create_page' => 'Create people',
        'display_page' => 'display people',
        'login_page' => 'Login page',
        // PAGES
        'man' => 'man',
        'woman' => 'woman',
        'other' => 'other',
        'admin' => 'administrator',
        'user' => 'user',
        'people' => 'People',
        'id' => 'Id',
        'firstname' => 'Firstname',
        'lastname' => 'Lastname',
        'age' => 'Age',
        'mail' => 'Mail',
        'gender' => 'Gender',
        'role' => 'Role',
        'modify' => 'Modify',
        'modify_icon' => 'MOD',
        'delete' => 'Delete',
        'delete_icon' => 'SUP',
        'data' => 'Data',
        'year_old' => 'Y.Old',
        'select_gender' => 'Select gender',
        'select_role' => 'Select role',
        'create' => 'Create',
        'cancel' => 'Cancel',
        'modify_data' => 'Modify Data',
        'username' => 'User',
        'password' => 'Password',
        'connect' => 'Connection',
        // MESSAGE
        'create_message_error' => 'Please fill all the fields',
        'create_message_success' => 'People created successfully',
        'delete_message_success' => 'People deleted from the DB',
        'guest' => 'Guest',
        'logout' => 'Logout',
        'hello_message'=> 'Hello ',
        'home_message' => 'You are connected as : ',
        'home_message_2' => 'You must be connected to access this page',
        'home_message_3' => 'Go to the ',
    );
?>