<?php
    $languageArray = array(
        //TITLE
        'Accueil.php' => 'ACCUEIL V6',
        'Creer_personne.php' => 'CRÉER PERSONNE V6',
        'Afficher_personne.php' => 'AFFICHER PERSONNE V6',
        'Modifier_personne.php' => 'MODIFIER PERSONNE V6',
        'Login.php' => 'CONNEXION V6',
        // LANGUAGE
        'language' => '🌍 Choisir une langue',
        'french' => '🇫🇷 Français',
        'english' => '🇬🇧 Anglais',
        'catalan' => '🏴‍☠️ Catalan',
        // LINK
        'home_page' => 'Retour à l\'accueil',
        'create_page' => 'Créer Personne',
        'display_page' => 'Afficher Personne',
        'login_page' => 'Page de connexion',
        // PAGES
        'man' => 'homme',
        'woman' => 'femme',
        'other' => 'autre',
        'admin' => 'administrateur',
        'user' => 'utilisateur',
        'people' => 'Personnes',
        'id' => 'Id',
        'firstname' => 'Prénom',
        'lastname' => 'Nom',
        'age' => 'Age',
        'mail' => 'Mail',
        'gender' => 'Genre',
        'role' => 'Rôle',
        'modify' => 'Modifier',
        'modify_icon' => 'MOD',
        'delete' => 'Supprimer',
        'delete_icon' => 'SUP',
        'data' => 'Informations',
        'year_old' => 'Ans',
        'select_gender' => 'Choisir un genre',
        'select_role' => 'Choisir un role',
        'create' => 'Créer',
        'cancel' => 'Annuler',
        'modify_data' => 'Modifier les informations',
        'username' => 'Nom d\'utilisateur',
        'password' => 'Mot de passe',
        'connect' => 'Connexion',
        'guest' => 'Invité',
        'logout' => 'Déconnexion',
        // MESSAGE
        'create_message_error' => 'Veuillez remplir tous les champs',
        'create_message_success' => 'Personne créée avec succès',
        'delete_message_success' => 'Personne supprimée de la BDD',
        'hello_message'=> 'Salut ',
        'home_message' => 'Vous êtes connecté en tant que : ',
        'home_message_2' => 'Vous devez être connecté pour accéder à cette page',
        'home_message_3' => 'Aller à la ',
    );
?>