<?php
    $languageArray = array(
        // TITLE
        'Accueil.php' => 'BENVINGUT V5',
        'Creer_personne.php' => 'CREAR PERSONA V5',
        'Afficher_personne.php' => 'VISUALITZACIÓ PERSONA V5',
        'Modifier_personne.php' => 'MODIFICAR PERSONA V5',
        'Login.php' => 'INICIAR SESSIÓ V5',
        // LANGUAGE
        'language' => '🌍 Trieu un idioma',
        'french' => '🇫🇷 francès',
        'english' => '🇬🇧 Anglès',
        'catalan' => '🏴‍☠️ Català',
        // LINK
        'home_page' => 'Tornar a casa',
        'create_page' => 'Crea una persona',
        'display_page' => 'Mostra la persona',
        'login_page' => 'Pàgina d\'inici de sessió',
        // PAGES
        'man' => 'mascle',
        'woman' => 'dones',
        'other' => 'altres',
        'admin' => 'administrador',
        'user' => 'usuari',
        'people' => 'Gent',
        'id' => 'id',
        'firstname' => 'Nom',
        'lastname' => 'Cognom',
        'age' => 'Edat',
        'mail' => 'Correu electrònic',
        'gender' => 'Gènere',
        'role' => 'Paper',
        'modify' => 'Modifica',
        'modify_icon' => 'MOD',
        'delete' => 'Suprimeix',
        'delete_icon' => 'SUP',
        'data' => 'Informació',
        'year_old' => 'Anys',
        'select_gender' => 'Selecciona el gènere',
        'select_role' => 'Selecciona el paper',
        'create' => 'Crear',
        'cancel' => 'Cancella',
        'modify_data' => 'Modifica les dades',
        'username' => 'Nom d\'usuari',
        'password' => 'Contrasenya',
        'connect' => 'Iniciar Sessió',
        'guest' => 'Convidat',
        'logout' => 'Tancar sessió',
        // MESSAGE
        'create_message_error' => 'Si us plau, ompli tots els camps',
        'create_message_success' => 'Persona creada correctament',
        'hello_message'=> 'Hola ',
        'home_message' => 'Has iniciat sessió com a : ',
        'home_message_2' => 'Heu d\'iniciar sessió per accedir a aquesta pàgina',
        'home_message_3' => 'Per anar al ',
    );
?>